# docker-compose -p wordpress up -d --build

version: '3.9'

services:
  db: 
    container_name: 'wp-db'
    image: mysql:8.0-debian
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - internal
    env_file:
      - ./config/db.env
    
  wordpress:
    container_name: 'wp-site'
    depends_on:
      - db
    image: wordpress:php8.1-apache
    ports:
      - "80:80"
    restart: always
    networks:
      - internal
    volumes:
      - wp_data:/var/www/html
    env_file:
      - ./config/wp.env

  phpmyadmin:
    container_name: 'wp-admin'
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - 88:80
    restart: always
    networks:
      - internal
    env_file:
      - ./config/ad.env

volumes:
  db_data: {}
  wp_data: {}

networks:
  internal: