# docker-compose -p wordpress up -d --build

version: '3.3'

services:
  db: 
    container_name: 'wp-db'
    image: mysql:8.0-debian
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - wordpress
    env_file:
      - ./config/db.env
    
  wordpress:
    container_name: 'wp-site'
    depends_on:
      - db
    image: wordpress:php8.1-apache
    ports:
      - "80:80"
    restart: always
    networks:
      - wordpress
    volumes:
      - wp_data:/var/www/html
    env_file:
      - ./config/wp.env

volumes:
  db_data: {}
  wp_data: {}

networks:
  wordpress: