version: '3.3'
name: 'wordpress-compose'
services:
  db: 
    container_name: 'wp-db'
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env
    
  wordpress:
    container_name: 'wp-site'
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wp.env

volumes:
  db_data: {}